mongodb:
  host: "![v5ds7yptZNPPWoYUaPiuy6OvX6vyH2o0ZVdgNe3MhaeRHTE+XG1Kiw==]"
  db: "![a+cogM3DLEA=]"
  username: "![8Tt+KpRES5eVLwW7ZFWb3w==]"
  password: "![2AD+0Mr7YSkcGGuJRkN47IApiOkluoI/]"
anypoint:
  autodiscovery: "16540396"